// Code generated by "stringer -type=deviceDescriptorType"; DO NOT EDIT.

package adb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DeviceAny-0]
	_ = x[DeviceSerial-1]
	_ = x[DeviceUsb-2]
	_ = x[DeviceLocal-3]
}

const _deviceDescriptorType_name = "DeviceAnyDeviceSerialDeviceUsbDeviceLocal"

var _deviceDescriptorType_index = [...]uint8{0, 9, 21, 30, 41}

func (i deviceDescriptorType) String() string {
	if i < 0 || i >= deviceDescriptorType(len(_deviceDescriptorType_index)-1) {
		return "deviceDescriptorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _deviceDescriptorType_name[_deviceDescriptorType_index[i]:_deviceDescriptorType_index[i+1]]
}
