// Code generated by "stringer -type=DeviceState"; DO NOT EDIT.

package adb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StateInvalid-0]
	_ = x[StateUnauthorized-1]
	_ = x[StateAuthorizing-2]
	_ = x[StateDisconnected-3]
	_ = x[StateOffline-4]
	_ = x[StateOnline-5]
	_ = x[StateHost-6]
}

const _DeviceState_name = "StateInvalidStateUnauthorizedStateAuthorizingStateDisconnectedStateOfflineStateOnlineStateHost"

var _DeviceState_index = [...]uint8{0, 12, 29, 45, 62, 74, 85, 94}

func (i DeviceState) String() string {
	if i < 0 || i >= DeviceState(len(_DeviceState_index)-1) {
		return "DeviceState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DeviceState_name[_DeviceState_index[i]:_DeviceState_index[i+1]]
}
